# DeepSource configuration for Azide Boron
# https://docs.deepsource.com/docs/core-analyzers

version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dialect = "typescript"

[[analyzers]]
name = "test-coverage"
enabled = true
