# Raichu (Production) environment overrides
app:
  name: 'The Bite-Sized Productivity Blog'
  shortName: 'The BSP Blog'
  description: 'Palatable sized content to supercharge your life'
  backgroundColor: '#ffffff'
seo:
  defaultTitle: 'The BSP Blog'
  titleTemplate: '%s | The BSP Blog'
  defaultDescription: The Bite-Sized Productivity from Team AtomiCloud
  siteName: 'The BSP Blog'
  locale: 'en_US'
  type: 'website'

site:
  url: 'https://blog.atomi.cloud'
  author: 'AtomiCloud Team'

social:
  linkedin: 'https://www.linkedin.com/company/atomicloud/'
  email: 'hello@atomi.cloud'
  bluesky: 'https://bsky.app/profile/atomicloud.bsky.social'
  reddit: 'https://www.reddit.com/user/AtomiCloudOfficial/'

legal:
  contactEmail: 'admin@atomi.cloud'
  dpoEmail: 'ernest@atomi.cloud'
  companyName: 'AtomiCloud'
