# Raichu (Production) environment overrides
app:
  name: 'The Bite-Sized Productivity Blog'
  shortName: 'The BSP Blog'
  description: 'Palatable sized content to supercharge your life'
  backgroundColor: '#ffffff'
seo:
  defaultTitle: 'The BSP Blog'
  titleTemplate: '%s | The BSP Blog'
  defaultDescription: The Bite-Sized Productivity from Team AtomiCloud
  siteName: 'The BSP Blog'
  locale: 'en_US'
  type: 'website'

site:
  url: 'https://blog.atomi.cloud'
  author: 'AtomiCloud Team'

social:
  twitter: 'https://twitter.com/azideboron'
  github: 'https://github.com/azideboron'
  discord: 'https://discord.gg/azideboron'
  youtube: 'https://youtube.com/@azideboron'
  tiktok: 'https://tiktok.com/@azideboron'
  linkedin: 'https://linkedin.com/company/azideboron'
  instagram: 'https://instagram.com/azideboron'
  telegram: 'https://t.me/azideboron'
  email: 'hello@azideboron.com'
  whatsapp: '1234567890'

legal:
  contactEmail: 'admin@atomi.cloud'
  dpoEmail: 'ernest@atomi.cloud'
  companyName: 'AtomiCloud'
